package frontend.BatlleNaval;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.MouseMotionAdapter;
import java.util.Observable;
import java.util.Observer;

/**
 * @author novoa
 */
public class BoatTable extends JFrame implements Observer {

    public static final int BoardWidth = 10;
    private final BoardManager boardManager;
    private String namePlayer;
    private JPanel backgroundPanel;
    private JButton btnAddBoat1Size;
    private JButton btnAddBoat2Size;
    private JButton btnAddBoat3Size;
    private JButton btnAddBoat4Size;
    private JButton btnSearchMatch;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JPanel jPanel1;
    private JLabel lblNumberBoat1Size;
    private JLabel lblNumberBoat2Size;
    private JLabel lblNumberBoat3Size;
    private JLabel lblNumberBoat4Size;
    private JPanel mainBoard;
    private JPanel mainBoard2;
    private JLabel textTittle;

    public BoatTable(BoardManager boardManager, ActionListener actionListener) {
        initComponents(actionListener);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        mainBoard.setLayout(new GridLayout(BoardWidth, BoardWidth));
        this.boardManager = boardManager;
        btnAddBoat4Size.addMouseListener(Mouse.getMyMouse());
        btnAddBoat3Size.addMouseListener(Mouse.getMyMouse());
        btnAddBoat2Size.addMouseListener(Mouse.getMyMouse());
        btnAddBoat1Size.addMouseListener(Mouse.getMyMouse());
        btnAddBoat4Size.setName("btnAddBoat4Size");
        btnAddBoat3Size.setName("btnAddBoat3Size");
        btnAddBoat2Size.setName("btnAddBoat2Size");
        btnAddBoat1Size.setName("btnAddBoat1Size");
        fillMainBoardStart();

    }

    public void setNamePlayer(String namePlayer) {
        this.namePlayer = namePlayer;
        this.textTittle.setText("Bienvenido a Batalla Naval: " + namePlayer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(ActionListener actionListener) {
        this.btnSearchMatch = new JButton("Iniciar");
        this.btnSearchMatch.addActionListener(actionListener);
        this.btnSearchMatch.setActionCommand(Actions.SEARCH_MATCH);
        this.setBounds(10, 10, 200, 100);


        backgroundPanel = new JPanel();

        textTittle = new JLabel();
        mainBoard = new JPanel();
        mainBoard2 = new JPanel();
        jPanel1 = new JPanel();
        btnAddBoat4Size = new JButton();
        btnAddBoat3Size = new JButton();
        btnAddBoat1Size = new JButton();
        btnAddBoat2Size = new JButton();
        lblNumberBoat2Size = new JLabel();
        lblNumberBoat4Size = new JLabel();
        lblNumberBoat3Size = new JLabel();
        lblNumberBoat1Size = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(102, 102, 255));

        textTittle.setFont(new Font("Stencil", Font.PLAIN, 24)); // NOI18N
        textTittle.setForeground(new Color(255, 255, 255));
        textTittle.setHorizontalAlignment(SwingConstants.CENTER);
        textTittle.setText("Bienvenido a Batalla Naval: " + namePlayer);
        textTittle.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                textMouseMoved(evt);
            }
        });
        backgroundPanel.add(textTittle);

        mainBoard.setBackground(new Color(255, 255, 255));
//        mainBoard.setLayout(new java.awt.GridLayout());
        backgroundPanel.add(mainBoard);
//        backgroundPanel.add(mainBoard);

        jPanel1.setBackground(new Color(255, 255, 255));

        btnAddBoat4Size.setText("Barco : 4");
        btnAddBoat4Size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBoat4SizeActionPerformed(evt);
            }
        });

        btnAddBoat3Size.setText("Barco: 3");
        btnAddBoat3Size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBoat3SizeActionPerformed(evt);
            }
        });

        btnAddBoat1Size.setText("Barco: 1");
        btnAddBoat1Size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBoat1SizeActionPerformed(evt);
            }
        });

        btnAddBoat2Size.setText("Barco: 2");
        btnAddBoat2Size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBoat2SizeActionPerformed(evt);
            }
        });

        lblNumberBoat2Size.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumberBoat2Size.setText("3");

        lblNumberBoat4Size.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumberBoat4Size.setText("3");

        lblNumberBoat3Size.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumberBoat3Size.setText("3");

        lblNumberBoat1Size.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumberBoat1Size.setText("2");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("Barcos Restantes");

        jLabel6.setText("Barcos Disponibles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(19, 19, 19).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(btnAddBoat2Size).addComponent(btnAddBoat1Size).addComponent(btnAddBoat3Size).addComponent(btnAddBoat4Size)).addGap(18, 18, 18).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(lblNumberBoat2Size, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblNumberBoat1Size, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblNumberBoat4Size, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(lblNumberBoat3Size, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(15, Short.MAX_VALUE)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addComponent(jLabel6).addGap(36, 36, 36)))));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(11, 11, 11).addComponent(jLabel5).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnAddBoat4Size).addComponent(lblNumberBoat4Size, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(29, 29, 29).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnAddBoat3Size).addComponent(lblNumberBoat3Size, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(26, 26, 26).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblNumberBoat2Size, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(btnAddBoat2Size)).addGap(18, 18, 18).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(lblNumberBoat1Size, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(btnAddBoat1Size)).addContainerGap(32, Short.MAX_VALUE)));

        backgroundPanel.add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE));
        backgroundPanel.add(btnSearchMatch);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_textMouseMoved

    private void btnAddBoat4SizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBoat4SizeActionPerformed

    }//GEN-LAST:event_btnAddBoat4SizeActionPerformed

    private void btnAddBoat3SizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBoat3SizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddBoat3SizeActionPerformed

    private void btnAddBoat1SizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBoat1SizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddBoat1SizeActionPerformed

    private void btnAddBoat2SizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBoat2SizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddBoat2SizeActionPerformed

    public JPanel getMainBoard() {
        return mainBoard;
    }


    public void fillMainBoardStart() {
        mainBoard.setPreferredSize(new Dimension(350, 350));
        mainBoard.setLocation((backgroundPanel.getWidth() / 2) - (backgroundPanel.getWidth() / 2), (backgroundPanel.getHeight() / 2) - (backgroundPanel.getHeight() / 2));
        for (int i = 1; i <= BoardWidth; i++) {
            for (int j = 1; j <= BoardWidth; j++) {
                Cell currentPanel = new Cell((j + "," + i), boardManager, this);
                CellManager.getMyCellManager().getCellList().add(currentPanel);
                mainBoard.add(currentPanel.getPanel());
            }
        }


    }


    public void fillMainBoardRepaint() {
        this.repaint();
        mainBoard.removeAll();
        mainBoard.revalidate();
        for (int i = 1; i <= BoardWidth; i++) {
            for (int j = 1; j <= BoardWidth; j++) {
                Cell currentPanel = CellManager.getMyCellManager().search(i, j);
                CellManager.getMyCellManager().getCellList().add(currentPanel);
                mainBoard.add(currentPanel.getPanel());
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables

    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable currentPanel, Object arg) {
        try {
            if (currentPanel instanceof Cell) {
                switch (Mouse.getMyMouse().getComponentClicked().getName()) {
                    case "btnAddBoat4Size" -> {
                        int numberBoats4 = Integer.parseInt(lblNumberBoat4Size.getText()) - 1;
                        if (numberBoats4 >= 0) {
                            lblNumberBoat4Size.setText(Integer.toString(numberBoats4));
                        } else {
                            CellManager.getMyCellManager().setBoatAvaliable4(false);
                        }
                    }
                    case "btnAddBoat3Size" -> {
                        int numberBoats3 = Integer.parseInt(lblNumberBoat3Size.getText()) - 1;
                        if (numberBoats3 >= 0) {
                            lblNumberBoat3Size.setText(Integer.toString(numberBoats3));
                        } else {
                            CellManager.getMyCellManager().setBoatAvaliable3(false);
                        }
                    }
                    case "btnAddBoat2Size" -> {
                        int numberBoats2 = Integer.parseInt(lblNumberBoat2Size.getText()) - 1;
                        if (numberBoats2 >= 0) {
                            lblNumberBoat2Size.setText(Integer.toString(numberBoats2));
                        } else {
                            CellManager.getMyCellManager().setBoatAvaliable2(false);
                        }
                    }
                    case "btnAddBoat1Size" -> {
                        int numberBoats1 = Integer.parseInt(lblNumberBoat1Size.getText()) - 1;
                        if (numberBoats1 >= 0) {
                            lblNumberBoat1Size.setText(Integer.toString(numberBoats1));
                        } else {
                            CellManager.getMyCellManager().setBoatAvaliable1(false);
                        }
                    }
                    default -> throw new AssertionError();
                }

            }
        } catch (Exception e) {
        }
    }

}
