/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.BatlleNaval;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author novoa
 */
public class BoatTable extends javax.swing.JFrame {

    /**
     * Creates new form BoatTable
     */
    
    private CellManager cellList;
    public static final int BoardWidth = 8;
    private BoardManager boardManager;
    
    public BoatTable(BoardManager boardManager) {
        initComponents();
        cellList = new CellManager();
        mainBoard.setLayout(new GridLayout(BoardWidth,BoardWidth));
        this.boardManager = boardManager;
        fillMainBoardStart();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        text = new javax.swing.JLabel();
        mainBoard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(102, 102, 255));

        text.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Bienvenido a Batalla Naval");
        text.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                textMouseMoved(evt);
            }
        });
        backgroundPanel.add(text);

        mainBoard.setBackground(new java.awt.Color(255, 255, 255));
        mainBoard.setLayout(new java.awt.GridLayout());
        backgroundPanel.add(mainBoard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_textMouseMoved

    public JPanel getMainBoard() {
        return mainBoard;
    }

    
    
    
    public void fillMainBoardStart(){
        mainBoard.setPreferredSize(new Dimension(350, 350));
        mainBoard.setLocation((backgroundPanel.getWidth()/2)-(backgroundPanel.getWidth()/2), (backgroundPanel.getHeight()/2)-(backgroundPanel.getHeight()/2));
        for (int i = 1; i <= BoardWidth; i++) {
            for (int j = 1; j <= BoardWidth; j++) {
                Cell currentPanel = new Cell((j + "," + i),cellList,boardManager);
                cellList.getCellList().add(currentPanel);
                mainBoard.add(currentPanel.getPanel());
            }
        }
    }
    
    
    public void fillMainBoardRepaint(){
        this.repaint();
        mainBoard.removeAll();
        mainBoard.revalidate();
        for (int i = 1; i <= BoardWidth; i++) {
            for (int j = 1; j <= BoardWidth; j++) {
                Cell currentPanel = cellList.search(i, j);
                cellList.getCellList().add(currentPanel);
                mainBoard.add(currentPanel.getPanel());
            }
        }
    }
    
    
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoatTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoatTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoatTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoatTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new BoatTable().setVisible(true);
////            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel mainBoard;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
